name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (Elixir ${{ matrix.elixir }}, OTP ${{ matrix.erlang }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: "25.3"
            elixir: "1.14"
            lint: true
            coverage: true
          - erlang: "24.3"
            elixir: "1.12"
    env:
      MIX_ENV: test

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: "3.20.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-otp${{ matrix.erlang }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix do deps.get --only test, deps.compile

      - name: Check for unused dependencies
        run: mix do deps.get, deps.unlock --check-unused
        if: ${{ matrix.lint && steps.cache-deps.outputs.cache-hit != 'true'}}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Check mix format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test
